---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Inline-Filters-Ragel
no_index:
  directory:
    - t
    - inc
requires:
  File::Temp: 0
resources:
  bugtracker: https://github.com/hoytech/Inline-Filters-Ragel/issues
  repository: git://github.com/hoytech/Inline-Filters-Ragel.git
version: 0.101
